name: todolistapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  awesome_dialog: ^3.2.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_background: ^1.0.8
  flutter_background_service: ^5.0.5
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  geolocator: ^11.0.0
  go_router: ^14.6.2
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  workmanager: ^0.5.2
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  uuid: ^4.4.0
  file_picker: ^8.0.0
  video_player: ^2.9.2
  # chewie: ^1.7.5
  video_thumbnail: ^0.5.3
  logger: ^2.0.2
  path_provider: ^2.1.4
  pie_chart: ^5.4.0


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  showcaseview: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
