name: todolistapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  dio: ^5.0.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  animate_do: ^3.3.4
  socket_io_client: ^2.0.3+1
  geolocator: ^11.0.0
  workmanager: ^0.5.2
  flutter_background: ^1.0.8
  flutter_background_service: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  showcaseview: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
